### ISSUE TITLE
Add export GetVehiclesByCategory()

### ISSUE THREAD

**Issue by Manason** [Qbox-project/qbx_core#183]
### The problem

It's a common operation to create a map of categories to vehicles. adminmenu & vehicleshop both do it. This results in duplicate code across resources implementing the same feature

### Ideal solution

create a centralized core export to reduce duplicate code in other resources for a common operation.

### Alternative solutions

add a utility function to the utility module which converts the vehicles to the desired format. If we go this route maybe we could make a generic remapper function which inputs the key to map on so it can be re-used to create a map of hashes to vehicles, or for other tables as well.

At the very least, if going the module route, deprecate GetVehiclesByName and GetVehiclesByHash and create GetVehicles

**Comment by TonybynMp4** [comment]
So i guess, if i understand what you'd like correctly, that you'd want a function like this?
`
---@param vehicle model | hash
---@param category string
GetVehicles(vehicle, category)
`

**Comment by Manason** [comment]
> So i guess, if i understand what you'd like correctly, that you'd want a function like this?
> 
> ```lua
> ---@param vehicle model | hash
> ---@param category string
> function GetVehicles(vehicle, category)
> ...
> end)
> ```

Negative. I mean a function that returns all the vehicles, mapped by category so that I can do exports.qbx_core:GetVehiclesByCategory()[category]

**Comment by TonybynMp4** [comment]
I'm talking about that 🤔 
> At the very least, if going the module route, deprecate GetVehiclesByName and GetVehiclesByHash and create GetVehicles

**Comment by Manason** [comment]
> I'm talking about that 🤔
> 
> > At the very least, if going the module route, deprecate GetVehiclesByName and GetVehiclesByHash and create GetVehicles

Given that we already store this mapping in core, I think the export route is preferred over the module solution.
