### ISSUE TITLE
Black screen after selecting existing character

### ISSUE THREAD

**Issue by tom-osborne** [Qbox-project/qbx_core#185]
### Summary

When selecting a previously created character you get stuck on a black screen

### Reproduction

1. Create a new server using qbx-lean recipe (possibly same on main recipe, but definitely on lean).
2. Leave server on completely default settings (no server.cfg changes)
3. Create a character and save character.
4. use /logout or 'logout' in F8 console
5. Select character previously created
6. Stuck on black screen.

No client side errors appear, but an error message from qbx_smallresources seems to appear when logging in (likely unrelated)
![image](https://github.com/Qbox-project/qbx_core/assets/96954031/608b2ac4-9e7b-4af6-a653-ab166e29643e)

### Expected behavior

Expect to be able to login and spawn

### Actual behavior

Black screen after character selection (existing characters only)

### Last Updated

3 hours ago

### Custom Resources

Default qbox-lean recipe

### Resource Rename

N/A

**Comment by tom-osborne** [comment]
I suspect the issue is being caused by these lines of code, which require qb-spawn. qb-spawn is missing from the qbx-lean recipe

https://github.com/Qbox-project/qbx_core/blob/main/client/character.lua#L298-299

**Comment by tom-osborne** [comment]
Adding qbx_spawn, qbx_apartments and qbx_interior fixes this issue. All three are required as they depend on each other.

**Comment by tom-osborne** [comment]
Tested with `default-spawn` branch (ref #184) and this fixed the issue.

**Comment by MafewTM** [comment]
So has this been resolved?

**Comment by MafewTM** [comment]
> Tested with `spawn-default` branch (ref #184 [ef4e19c](https://github.com/Qbox-project/qbx_core/commit/ef4e19c7b5ab147344fe6645578cc755a09129ad)) and this fixed the issue.

So has this been resolved?

**Comment by tom-osborne** [comment]
> > Tested with `spawn-default` branch (ref #184 [ef4e19c](https://github.com/Qbox-project/qbx_core/commit/ef4e19c7b5ab147344fe6645578cc755a09129ad)) and this fixed the issue.
> 
> So has this been resolved?

Yes, fixed as described
