### ISSUE TITLE
Player_buckets

### ISSUE THREAD

**Issue by DevX32** [Qbox-project/qbx_core#190]
### Summary

qbx_core/server/events.lua:36: attempt to index a nil value (field 'Player_Buckets')

### Reproduction

see error

### Expected behavior

should not show this

### Actual behavior

getting error

### Last Updated

today

### Custom Resources

none

### Resource Rename

no

**Comment by Manason** [comment]
Unable to reproduce. Please list specific steps for one to do that causes the error
