### ISSUE TITLE
Character Creation Better Error Checking

### ISSUE THREAD

**Issue by Manason** [Qbox-project/qbx_core#197]
### The problem

When creating a character there are rules and checks on the creation fields. For example, the first and last name must be capitalized. Failing one of these checks results in clearing of all fields.

### Ideal solution

- Just fix the issue for the user when it makes sense (if first letter is required to be capital, just change it for them etc)

### Alternative solutions

- Correct fields should not be cleared & user should be told which fields are incorrect and why
- OR redo the UI using NUI to unlock powerful form features such as taking action on errors while the user is typing, highlighting error boxes, etc.

**Comment by MafewTM** [comment]
firstname, lastname, and nationality fields automatically capitalize the first letter of each word with the most recent commit mentioned above. user will still get kicked back and forced to reenter everything if words from the profanity list are used. unable to keep field contents and let user know which field is invalid with the current input dialog.
