### ISSUE TITLE
some things like ox_inv target and illenium-appreance need changes /bridge

### ISSUE THREAD

**Issue by DevX32** [Qbox-project/qbx_core#203]
### Summary

cash not syncing

### Reproduction

using the appreance

### Expected behavior

sync smoothly

### Actual behavior

not syncing

### Last Updated

today

### Custom Resources

none

### Resource Rename

no

**Comment by tom-osborne** [comment]
> Reproduction
using the appreance

This makes no sense. These should be clear concise steps to reproduce the issue.

You have not provided any information that the devs can use.

**Comment by DevX32** [comment]
> > Reproduction
> > using the appreance
> 
> This makes no sense. These should be clear concise steps to reproduce the issue.
> 
> You have not provided any information that the devs can use.

this is for new core changes i talked to mana for this

**Comment by Manason** [comment]
Reproduction steps should be clear steps to reproduce the issue. For example

1. give yourself $1000
2. spend some money by using the clothing shop
3. notice that you have less than $1,000
4. F8 quit
5. rejoin
6. notice that you now have $1,000 in your inventory again

Are these reproduction steps correct?

**Comment by DevX32** [comment]
> Reproduction steps should be clear steps to reproduce the issue. For example
> 
> 1. give yourself $1000
> 2. spend some money by using the clothing shop
> 3. notice that the money isnt removing
> 4. F8 quit
> 5. rejoin
> 6. notice that you dont have money in your inventory its removed

**Comment by TonybynMp4** [comment]
> > Reproduction steps should be clear steps to reproduce the issue. For example
> > 
> > 1. give yourself $1000
> > 2. spend some money by using the clothing shop
> > 3. notice that the money isnt removing
> > 4. F8 quit
> > 5. rejoin
> > 6. notice that you dont have money in your inventory its removed

Unable to reproduce the bug, check that everything is up to date maybe 🤷🏻

**Comment by Manason** [comment]
Are you encountering this bug on a fresh recipe install?

**Comment by Manason** [comment]
Can you provide a video? Tony was unable to reproduce using the steps shown

**Comment by DevX32** [comment]
> Can you provide a video? Tony was unable to reproduce using the steps shown

just i need to know the money sync is related to which script core inv or??
