### ISSUE TITLE
cannot use vehicle keys because export is only for qbx_vehiclekeys

### ISSUE THREAD

**Issue by alberttheprince** [Qbox-project/qbx_core#209]
### Summary

unless you use qbx_vehiclekeys, givekeys breaks

### Reproduction

use any vehiclekey resource other than qbx_vehiclekeys. For example qb-vehiclekeys.

### Expected behavior

expected behavior is that regardless of what vehiclekey system you use you should be able to trigger the event.

### Actual behavior

Car ownership, and a number of other car related things break due to car keys not being given to players.

### Additional context

Maybe move this out of core?

### Last Updated

Today

### Custom Resources

modified qb-vehiclekeys/custom vehiclekeys resource

### Resource Rename

no

**Comment by Manason** [comment]
We should probably just move the command out of core. Seems like the vehicle key resources should own those commands.

**Comment by Manason** [comment]
On second thought moving the command might break backwards compatibility. Maybe best to trigger a 'qbx_core:server:giveKeys' event then?

**Comment by SantyR0** [comment]
> On second thought moving the command might break backwards compatibility. Maybe best to trigger a 'qbx_core:server:giveKeys' event then?

Sorry for asking, but where should be "qbx_core:server:giveKeys" be placed?

**Comment by Manason** [comment]
> > On second thought moving the command might break backwards compatibility. Maybe best to trigger a 'qbx_core:server:giveKeys' event then?
> 
> Sorry for asking, but where should be "qbx_core:server:giveKeys" be placed? Also, "use any vehiclekey resource other than qbx_vehiclekeys. For example qb-vehiclekeys." it seems that even in fresh recipes, even with the qbx-vehiclekeys this problem persists when taking vehicles out from impound/garage.

Instead of the export, triggering the event within the /giveKeys command in core would allow any vehicle key resource to consume the event to give keys
