### ISSUE TITLE
jim-payments maybe bridge not working 100%? qb script to qbx

### ISSUE THREAD

**Issue by D3monkat** [Qbox-project/qbx_core#210]
### Summary

bridge not working

### Reproduction

when using jim-payments and using jim-catcafe or trying to use the cash register command it will throw an error when trying to locate nearest players.

### Expected behavior

should pull the closest players and offer to charge the player

### Actual behavior

error codes:
 [ script:jim-payments] SCRIPT ERROR: @jim-payments/server/server.lua:246: attempt to index a nil value (local 'P')
[ script:jim-payments] > TriggerCallback (@qbx_core/bridge/qb/server/main.lua:81)
[ script:jim-payments] > handler (@qbx_core/bridge/qb/server/main.lua:43)
[     script:qbx_core] SCRIPT ERROR: error object is not a string

### Last Updated

today

### Custom Resources

jim-payments

### Resource Rename

no

**Comment by CarlBishop** [comment]
local P = QBCore.Functions.GetPlayer(v)
		onlineList[#onlineList+1] = { value = tonumber(v), text = "["..v.."] - "..P.PlayerData.charinfo.firstname..' '..P.PlayerData.charinfo.lastname  }
	end

**Comment by CarlBishop** [comment]
`local P = QBCore.Functions.GetPlayer(v)
		onlineList[#onlineList+1] = { value = tonumber(v), text = "["..v.."] - "..P.PlayerData.charinfo.firstname..' '..P.PlayerData.charinfo.lastname  }
	end `

**Comment by Manason** [comment]
> local P = QBCore.Functions.GetPlayer(v) onlineList[#onlineList+1] = { value = tonumber(v), text = "["..v.."] - "..P.PlayerData.charinfo.firstname..' '..P.PlayerData.charinfo.lastname } end

What is the value of v? Could you print it or show additional preceding lines?

**Comment by CarlBishop** [comment]
I'm only helping, I cannot reproduce the issue since I guess it happens only when a player is billing another player and I do not have any server with players... so the original issue poster should reply.

By the way this is the server callback:

`QBCore.Functions.CreateCallback('jim-payments:MakePlayerList', function(source, cb)
	local onlineList = {}
	for _, v in pairs(QBCore.Functions.GetPlayers()) do
		local P = QBCore.Functions.GetPlayer(v)
		onlineList[#onlineList+1] = { value = tonumber(v), text = "["..v.."] - "..P.PlayerData.charinfo.firstname..' '..P.PlayerData.charinfo.lastname  }
	end
	cb(onlineList)
end)`

And this is called by:

`RegisterNetEvent('jim-payments:client:Charge', function(data, outside)
	--Check if player is using /cashregister command
	if not outside and not onDuty and data.gang == nil then triggerNotify(nil, Loc[Config.Lan].error["not_onduty"], "error") return end
	local newinputs = {} -- Begin qb-input creation here.
	if Config.List then -- If nearby player list is wanted:
		--Retrieve a list of nearby players from server
		local p = promise.new() QBCore.Functions.TriggerCallback('jim-payments:MakePlayerList', function(cb) p:resolve(cb) end)
		local onlineList = Citizen.Await(p)
		local nearbyList = {}
		--Convert list of players nearby into one qb-input understands + add distance info
		for _, v in pairs(QBCore.Functions.GetPlayersFromCoords(GetEntityCoords(PlayerPedId()), Config.PaymentRadius)) do
			local dist = #(GetEntityCoords(GetPlayerPed(v)) - GetEntityCoords(PlayerPedId()))
			for i = 1, #onlineList do
				if onlineList[i].value == GetPlayerServerId(v) then
					if v ~= PlayerId() or Config.Debug then
						nearbyList[#nearbyList+1] = { value = onlineList[i].value, text = onlineList[i].text..' ('..math.floor(dist+0.05)..'m)' }
					end
				end
			end
		end
		--If list is empty(no one nearby) show error and stop
		if not nearbyList[1] then triggerNotify(nil, Loc[Config.Lan].error["no_one"], "error") return end
		newinputs[#newinputs+1] = { text = " ", name = "citizen", type = "select", options = nearbyList }
	else -- If Config.List is false, create input text box for ID's
		newinputs[#newinputs+1] = { type = 'text', isRequired = true, name = 'citizen', text = Loc[Config.Lan].menu["cus_id"] }
	end
	--Check if image was given when opening the regsiter
	local img = data.img or ""
	if not string.find(img, "<") then img = "<center><p><img src="..img.." width=100px></p>" end
	--Continue adding payment options to qb-input
	newinputs[#newinputs+1] = { type = 'radio', name = 'billtype', text = Loc[Config.Lan].menu["type"], options = { { value = "cash", text = Loc[Config.Lan].menu["cash"] }, { value = "bank", text = Loc[Config.Lan].menu["card"] } } }
	newinputs[#newinputs+1] = { type = 'number', isRequired = true, name = 'price', text = Loc[Config.Lan].menu["amount_charge"] }
	--Grab Player Job name or Gang Name if needed
	local label = PlayerJob.label
	local gang = false
	if data.gang then label = PlayerGang.label gang = true end
	local dialog = exports['qb-input']:ShowInput({ header = img..label..Loc[Config.Lan].menu["cash_reg"], submitText = Loc[Config.Lan].menu["send"], inputs = newinputs})
	if dialog then
		if not dialog.citizen or not dialog.price then return end
		TriggerServerEvent('jim-payments:server:Charge', dialog.citizen, dialog.price, dialog.billtype, data.img, outside, gang)
	end
end)`

I guess the nil value is because there was no nearby player, because this code lack for check about nul value, it should contain:

`	for _, v in pairs(QBCore.Functions.GetPlayers()) do
		local P = QBCore.Functions.GetPlayer(v)
		if P ~= nil then
			onlineList[#onlineList+1] = { value = tonumber(v), text = "["..v.."] - "..P.PlayerData.charinfo.firstname..' '..P.PlayerData.charinfo.lastname  }
		end
	end`

**Comment by D3monkat** [comment]
when i go to bill another player. that gets called but it throws the error above.

**Comment by Manason** [comment]
I suspect https://github.com/Qbox-project/qbx_core/pull/215 should fix this. Can you pull latest commit and try again?
