### ISSUE TITLE
[Bug]Can't seem to place props using any script

### ISSUE THREAD

**Issue by l3oncoder** [Qbox-project/qbx_core#212]
### Summary

prop placement

### Reproduction

using cdn-fuel or any fuel script that uses hose and fuel nozzle,

The nozzle will spawn and disappear.

### Expected behavior

To be able to place or spawn props.

### Actual behavior

using cdn-fuel or any fuel script that uses hose and fuel nozzle,

The nozzle will spawn and disappear.

### Last Updated

yesterday

### Custom Resources

none

### Resource Rename

none

**Comment by Manason** [comment]
https://qbox-project.github.io/faq#entities-keep-dissapearing-when-i-try-to-spawn-them

**Comment by l3oncoder** [comment]
thanks @Manason  much respect
