### ISSUE TITLE
qbx_core failed to load in the server

### ISSUE THREAD

**Issue by gringoDiaz** [Qbox-project/qbx_core#219]
### Summary

qbx_core error

### Reproduction

Every time you login to the server qbx_core default character selection not showing up and spawn you as a ped then have error says failed to load model

### Expected behavior

Error 

@qbx_core/client/character.lua:387: failed to load model '279228114' (waited 8.6ms)

### Actual behavior

You load the server as a ped not in your default character

### Additional context

![image](https://github.com/Qbox-project/qbx_core/assets/63420825/a5f98451-cbf0-4d36-afa8-28f906fd57a4)

### Last Updated

today

### Custom Resources

no

### Resource Rename

no

**Comment by SKITTLE6969** [comment]
@gringoDiaz could you try my PR and let me know asap?

**Comment by gringoDiaz** [comment]
@SKITTLE6969 I've try the PR and it fixed the error but i takes time for the model to load

**Comment by SKITTLE6969** [comment]
> @SKITTLE6969 I've try the PR and it fixed the error but i takes time for the model to load

you can reduce the time from the Config.LoadingModelsTimeout = 10000 to something lower

**Comment by gringoDiaz** [comment]
Yes, it helps i tried to lower it to 5000
