### ISSUE TITLE
Default Spawn config does nothing, player gets spawned through fivem default map system thingy

### ISSUE THREAD

**Issue by SomeRandomNomNom** [Qbox-project/qbx_core#225]
### Summary

The Config for Default Spawn doesnt Apply, the Player gets Spawned to a location of fivem-map-skater.

### Reproduction

1. use the lean recipe
2. create character
3. get spawned to x = 1602.39, y = 6623.02, z = 15.8417  (spawnpoint from fivem-map-skater)
4. Cry

### Expected behavior

get spawned to the default coords

### Actual behavior

not get spawned to default coords

### Last Updated

today

### Custom Resources

nah

### Resource Rename

nah

**Comment by MafewTM** [comment]
Not able to reproduce on newest version of core. defaultSpawn works as intended.
