### ISSUE TITLE
Players can see each other during character selection

### ISSUE THREAD

**Issue by Manason** [Qbox-project/qbx_core#226]
### Summary

Players are in the same bucket, so can see and hear each other when in the same character selection location

### Reproduction

1. Remove all character selection locations except for 1
2. Have someone else load into character selection
3. Load in yourself
4. Observe that you can see each other and hear each other

### Expected behavior

You wouldn't be able to see nor hear other players selecting characters

### Actual behavior

You can see and hear other players selecting characters

### Additional context

This is due to not putting players in different buckets on load-in due to a more severe bug associated with that. See https://github.com/Qbox-project/qbx_core/pull/223

### Last Updated

N/A

### Custom Resources

N/A

### Resource Rename

N/A

**Comment by alberttheprince** [comment]
Is this still a bug? This is an unfortunate side effect of bucketing not working correctly correct? And why where the characters are kept and the camera displays the preview character are separate in multichar.

**Comment by Manason** [comment]
> Is this still a bug? This is an unfortunate side effect of bucketing not working correctly correct? And why where the characters are kept and the camera displays the preview character are separate in multichar.

We intentionally turned off bucketing, because it was causing a more severe bug. This is still an open issue affecting those using the built-in multi char.

**Comment by Manason** [comment]
I don't believe this has yet been addressed. #248 was rolled back.

**Comment by ChatDisabled** [comment]
Issue itself of routing buckets not working with oal has been fixed by Cfx https://github.com/citizenfx/fivem/pull/2286

**Comment by Manason** [comment]
> Issue itself of routing buckets not working with oal has been fixed by Cfx [citizenfx/fivem#2286](https://github.com/citizenfx/fivem/pull/2286)

Yes, but we still need to re-implement them.

**Comment by mafewtm** [comment]
Should be fixed as of #445
