### ISSUE TITLE
qbcore bridge compatibility issue - errors with GetPlate function

### ISSUE THREAD

**Issue by CarlBishop** [Qbox-project/qbx_core#230]
### Summary

Some qbcore resources that require vehicle plate generate errors on qbx_core

### Reproduction

I have seen this error on more than one legacy resources, for example renzu_garage but also qbx_vehiclesales.
When I recall the vehicle spawn event, the following error appear on client side:
![image](https://github.com/Qbox-project/qbx_core/assets/12203647/2b018eea-e7cb-41b1-855b-4e75bc00729c)

Generally this is associated with GetVehicleProperties

### Expected behavior

I expect no error from the qbcore bridge on qbx_core

### Actual behavior

The error cause the vehicle to spawn without some properties (like damages)

### Last Updated

yesterday

### Custom Resources

renzu_garage

### Resource Rename

no rename at all.

**Comment by Manason** [comment]
Could you test with this branch? https://github.com/Qbox-project/qbx_core/tree/vehicleinfo-test I have a suspicion as to the fix, but won't be able to test myself until much later tonight.

**Comment by CarlBishop** [comment]
I will do as soon as I come back home

**Comment by CarlBishop** [comment]
no, also worst
![image](https://github.com/Qbox-project/qbx_core/assets/12203647/1b7d7511-6e11-4ed6-b437-c29e4263de38)

**Comment by CarlBishop** [comment]
I do not have error on client side but on server side I have:
![image](https://github.com/Qbox-project/qbx_core/assets/12203647/da6872e6-e75a-4ab5-b3d7-f36f3fe6bdab)

And no vehicle property are applied

**Comment by ShomyTKD** [comment]
This error pops up for me as well, although I noticed it only when using /dv command

**Comment by Manason** [comment]
> This error pops up for me as well, although I noticed it only when using /dv command while inside a vehicle..

This makes sense. If you delete the vehicle, it no longer exists. Is this not the case with QB?

Also, I made a change to the branch if someone wants to test this again.

**Comment by CarlBishop** [comment]
Now better, no errors but no vehicle property are saved.
I don't know if it is caused by the script itself...

**Comment by CarlBishop** [comment]
The issue now seems to be related to vehicle props, may be it is the script itself i don't know

**Comment by Manason** [comment]
> The issue now seems to be related to vehicle props, may be it is the script itself i don't know

try on test-vehicleproperties branch

**Comment by CarlBishop** [comment]
After new change I have:
Damaged car
![image](https://github.com/Qbox-project/qbx_core/assets/12203647/c343a692-058e-4289-bb5d-7e190e34c183)

Parked car, deformation are saved but not the props (doors, windows etc...)
![image](https://github.com/Qbox-project/qbx_core/assets/12203647/57efcd22-d01a-4b1f-9d61-4f326ca7750d)
here the prints:
```
[    735282] [b2944_GTAProce]             MainThrd/ no script guid for vehicle 0 in SET_VEHICLE_HANDLING_FIELD
[    735282] [b2944_GTAProce]             MainThrd/ no script guid for vehicle 0 in SET_VEHICLE_HANDLING_FIELD
[    735282] [b2944_GTAProce]             MainThrd/ no script guid for vehicle 0 in SET_VEHICLE_HANDLING_FIELD
[    735282] [b2944_GTAProce]             MainThrd/ no script guid for vehicle 0 in SET_VEHICLE_HANDLING_FIELD
[    735313] [b2944_GTAProce]             MainThrd/ ^3Warning: NETWORK_GET_NETWORK_ID_FROM_ENTITY: no such entity (script ID 1115650)^7
[    735313] [b2944_GTAProce]             MainThrd/ ^3Warning: [entity] NETWORK_GET_NETWORK_ID_FROM_ENTITY: no such entity (script ID 1115650)^7
[    735469] [b2944_GTAProce]             MainThrd/ ^3Warning: [entity] GetNetworkObject: no object by ID 1115650^7
[    735469] [b2944_GTAProce]             MainThrd/ ^5[qbx_core] ^7[INFO] QBCore:Client:LeftVehicle	{
[    735469] [b2944_GTAProce]             MainThrd/     "driver": 0,
[    735469] [b2944_GTAProce]             MainThrd/     "haskeys": true,
[    735469] [b2944_GTAProce]             MainThrd/     "inseat": 0,
[    735469] [b2944_GTAProce]             MainThrd/     "seat": -1,
[    735469] [b2944_GTAProce]             MainThrd/     "vehicle": 0
[    735469] [b2944_GTAProce]             MainThrd/ }^7
[    735532] [b2944_GTAProce]             MainThrd/ ^5[qbx_core] ^7[INFO] QBCore:Client:EnteredVehicle	{
[    735532] [b2944_GTAProce]             MainThrd/     "driver": 197634,
[    735532] [b2944_GTAProce]             MainThrd/     "haskeys": true,
[    735532] [b2944_GTAProce]             MainThrd/     "inseat": 197634,
[    735532] [b2944_GTAProce]             MainThrd/     "plate": "49UAL186",
[    735547] [b2944_GTAProce]             MainThrd/     "seat": -1,
[    735547] [b2944_GTAProce]             MainThrd/     "vehicle": 1152770
[    735547] [b2944_GTAProce]             MainThrd/ }^7
```

**Comment by CarlBishop** [comment]
and at some point spawned a vehicle with a completely different plate
```
[    755313] [b2944_GTAProce]             MainThrd/ ^5[qbx_core] ^7[INFO] QBCore:Client:EnteredVehicle	{
[    755313] [b2944_GTAProce]             MainThrd/     "driver": 148994,
[    755313] [b2944_GTAProce]             MainThrd/     "haskeys": true,
[    755313] [b2944_GTAProce]             MainThrd/     "inseat": 148994,
[    755313] [b2944_GTAProce]             MainThrd/     "plate": "44YLM957",
[    755313] [b2944_GTAProce]             MainThrd/     "seat": -1,
[    755313] [b2944_GTAProce]             MainThrd/     "vehicle": 1366018
[    755313] [b2944_GTAProce]             MainThrd/ }^7
```

**Comment by Manason** [comment]
> and at some point spawned a vehicle with a completely different plate
> 
> ```
> 
> [    755313] [b2944_GTAProce]             MainThrd/ ^5[qbx_core] ^7[INFO] QBCore:Client:EnteredVehicle	{
> 
> [    755313] [b2944_GTAProce]             MainThrd/     "driver": 148994,
> 
> [    755313] [b2944_GTAProce]             MainThrd/     "haskeys": true,
> 
> [    755313] [b2944_GTAProce]             MainThrd/     "inseat": 148994,
> 
> [    755313] [b2944_GTAProce]             MainThrd/     "plate": "44YLM957",
> 
> [    755313] [b2944_GTAProce]             MainThrd/     "seat": -1,
> 
> [    755313] [b2944_GTAProce]             MainThrd/     "vehicle": 1366018
> 
> [    755313] [b2944_GTAProce]             MainThrd/ }^7
> 
> ```

Spawning a new vehicle with a different plate seems like an independent issue from the props. The props I think we have figured out, I just likely made some mistakes with the conversion code.

Any more info on the new plate?

**Comment by Manason** [comment]
Could you try again? I couldn't find an issue with the props, but I did put in a potential fix for the duplicate vehicles, which potentially affects the props?

**Comment by Manason** [comment]
Tested, this should be fixed now.
