### ISSUE TITLE
[REQUEST] mp ped health in core

### ISSUE THREAD

**Issue by MrNewb** [Qbox-project/qbx_core#246]
### The problem

Female peds on spawn are set to lower max health then male peds, normally its a lol moment but people are becoming more and more aware. In my core I use a small snippet to correct it on spawn and run it through a loop. Just figured id bring it up as I didnt see it in the medical.

### Ideal solution

if GetEntityMaxHealth(cache.ped) ~= 200 then 
SetEntityMaxHealth(cache.ped, 200)
SetEntityHealth(cache.ped, 200)

### Alternative solutions

could slap in small resources, id even stream in ped metas but I think its a fivem limitation

**Comment by MafewTM** [comment]
Hopefully fixed in latest qbx_medical commit
