### ISSUE TITLE
[BUG] Items.Shared additional info

### ISSUE THREAD

**Issue by MrNewb** [Qbox-project/qbx_core#256]
### Summary

Additional information used in items.shared is breaking core

### Reproduction

['hiqualitysoil']                	= {['name'] = 'hiqualitysoil', 					['label'] = 'Soil (HQ)', 						['weight'] = 0,		['type'] = 'item',		['image'] = 'hiqualitysoil.png',					['unique'] = false,		['useable'] = false,		['shouldClose'] = false,		['description'] = 'Soil for your plants', 						['uses'] = { ['IsSoil'] = true, ['Soil'] = 60, }, },

### Expected behavior

Core to load on login

### Actual behavior

no resources are able to get the core object

### Additional context

Some scripts pass additional information on the items.shared, doing this with qbox unfortunately breaks the core on load in.
I understand my situation could be from additional information I cant see because of escrow or to be blunt user error but here is an example

### Last Updated

today

### Custom Resources

N/A

### Resource Rename

N/A

**Comment by Manason** [comment]
Do you have some sort of error? I'm not sure I understand the bug here.

**Comment by MrNewb** [comment]
`[     81141] [b2944_GTAProce]             MainThrd/ Creating script environments for qbx_core
[     81172] [b2944_GTAProce]             MainThrd/ ^1SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:90: @qbx_core/bridge/qb/client/functions.lua:258: 'end' expected (to close 'function' at line 211) near 'TriggerServerEvent'^7
[     81172] [b2944_GTAProce]             MainThrd/ ^3> require^7 (^5@ox_lib/imports/require/client.lua^7:80)
[     81172] [b2944_GTAProce]             MainThrd/ ^3> fn^7 (^5@qbx_core/bridge/qb/client/main.lua^7:10)`

**Comment by MrNewb** [comment]
Disregard, 100000% user error. My bad
