### ISSUE TITLE
the boss menu is not working

### ISSUE THREAD

**Issue by Gideon-Developer** [Qbox-project/qbx_core#289]
### The problem

the boss menu is not working

### Ideal solution

the boss menu is not working

**Comment by solareon** [comment]
Going to need a few more details please. The boss menu is provided by the qbx_management resource. Have you updated that?

**Comment by Gideon-Developer** [comment]
I just run the recipe of your guys today and I didn't make any changes yet on my system for the framework so that's vanilla and can be and I see the boss menu doesn't open even if I add my custom wasabi script the same problem as the not open the menu and compactable with your guys

**Comment by Gideon-Developer** [comment]
i fix it

**Comment by Manason** [comment]
> i fix it

How did you fix it?

**Comment by Gideon-Developer** [comment]
> > i fix it
> 
> How did you fix it?

you must add it manually at on qbx_management/config/server.lua
