### ISSUE TITLE
New vehicles.lua update breaks qbx_vehicleshop

### ISSUE THREAD

**Issue by fsgdev** [Qbox-project/qbx_core#291]
### Summary

New vehicles.lua update breaks qbx_vehicleshop, 

### Reproduction

1. Download latest version of qbx_vehicleshop
2. Download latest version of qbx_core
3. Try to Swap Vehicle within qbx_vehicleshop, youll get an error when trying to go into any category apart from compacts

### Expected behavior

Should swap into the categories and let you access all vehicles

### Actual behavior

Gave me an error when trying to go into any category that isn't compacts.

### Last Updated

Today

### Custom Resources

None

### Resource Rename

No

**Comment by MafewTM** [comment]
The issue appears to be that because not all of the vehicles listed in the vehicles.lua are inside the qbx_vehicleshop config, its causing the categories to fail to load. I'm working on this right now

**Comment by fsgdev** [comment]
Is there a way you could make it so all of the vehicles inside vehicles.lua don’t have to be inside the qbx_vehicleshop config?

**Comment by MafewTM** [comment]
The PR I just created will allow the vehicle categories to load if not all vehicles from the vehicle.lua are present inside the config.vehicles. Once that PR is approved, it will close this issue if there is nothing else

**Comment by fsgdev** [comment]
There’s nothing else, I appreciate it

**Comment by MafewTM** [comment]
Yep. If you wanna test the PR out and make sure it works, feel free.

**Comment by fsgdev** [comment]
Just tested it and it works perfect now, appreciate the help and quick response
