### ISSUE TITLE
return qbx.getZoneName(coords) not working as intended

### ISSUE THREAD

**Issue by SKITTLE6969** [Qbox-project/qbx_core#319]
### Summary

my spawn selector uses getZoneName(coords) but after utils deprecate update its not properly returning the return qbx.getZoneName(coords) to spawn selector

### Additional context

![image](https://github.com/Qbox-project/qbx_core/assets/92496158/61e04876-9132-4538-9b19-d86e1445232b)

**Comment by MafewTM** [comment]
Do you have the new module in your core?

**Comment by solareon** [comment]
Does your fxmanifest for qbx_core match the github?

**Comment by solareon** [comment]
does cl_spawnselector load before the core?
