### ISSUE TITLE
string.trim(str)

### ISSUE THREAD

**Issue by SKITTLE6969** [Qbox-project/qbx_core#322]
### Summary

not returning the string.trim(str) properly like in utils

### Reproduction

![image](https://github.com/Qbox-project/qbx_core/assets/92496158/b75e3cb3-893c-4bb8-9af7-77193ab59cbc)

### Expected behavior

idk return the same as usual 

### Actual behavior

attached

### Additional context

.

### Last Updated

today

### Custom Resources

no

### Resource Rename

qbx_core

**Comment by D4isDAVID** [comment]
Lib was purposefully not implemented 1 to 1 with how utils was. This is an example of that; you cannot pass a `nil` value to `qbx.string.trim`.

**Comment by D4isDAVID** [comment]
In the case that I misinterpreted this issue, can you elaborate on when exactly this error happens?

**Comment by D4isDAVID** [comment]
Can you test this again with an updated core? I believe this should be fixed.
