### ISSUE TITLE
QBX.Shared not updating for new players

### ISSUE THREAD

**Issue by skizmx** [Qbox-project/qbx_core#351]
### Summary

exports CreateJobs/CreateGangs not updating for new players

### Reproduction

1. Create jobs using exports
2. login to server and spawn
3. print exports.qbx_core:GetJobs() on **client**

### Expected behavior

Newly logged in player should have the same QBX.Shared data as what was changed previously on the server

### Actual behavior

QBX.Shared does not fetch new data for newly logged in players

### Current Version

1.6.1

### Custom Resources

-

**Comment by BerkieBb** [comment]
That's because the export only changes the table on the server, it can't change it on a client that isn't in the server

**Comment by skizmx** [comment]
> That's because the export only changes the table on the server, it can't change it on a client that isn't in the server

yes, wouldn't it be great if players who just logged in also got the same data as players who are already on the server?

**Comment by BerkieBb** [comment]
Simple solution would just be getting the data from the server, otherwise we'd have to send the new data to new joining clients in the core

**Comment by Manason** [comment]
Re-doing the job/gang system at the moment. Will fix this bug with the changes.

**Comment by Manason** [comment]
This should be resolved as of v1.7.0. I'll keep the issue open until @skizmx can confirm
