### ISSUE TITLE
Backward compatibility broken after recent changes

### ISSUE THREAD

**Issue by SKITTLE6969** [Qbox-project/qbx_core#360]
### Summary

Did a fresh qbx_core replace just now and apparantly the backward compatibility is broken O_O 

![image](https://github.com/Qbox-project/qbx_core/assets/92496158/3d210c57-f2d9-4942-92ac-961cdcbf4a5a)

**Comment by DevX32** [comment]
@SKITTLE6969 thats bcz the groups thing stills wip so better use release verison

**Comment by DevX32** [comment]
@Manason

**Comment by Manason** [comment]
The issue is that bridge shared seems to be loading before server/groups. Not sure why exactly. Need to play around with it more.

**Comment by SKITTLE6969** [comment]
@Manason yup that solved the compatibility issue on the server, no more print on server console but let me check and get back to you with a client side test as well.

**Comment by SKITTLE6969** [comment]
reopening this since client side is still broken 
![image](https://github.com/Qbox-project/qbx_core/assets/92496158/bc0dc4e0-d3b1-46b6-842b-0dd981183424)

**Comment by SKITTLE6969** [comment]
@Manason client side still got issues

![image](https://github.com/Qbox-project/qbx_core/assets/92496158/85f13f5c-4c2d-4081-abf7-62fa2e71f463)

![image](https://github.com/Qbox-project/qbx_core/assets/92496158/36949f8b-1779-401f-8e7b-e500f256749c)
