### ISSUE TITLE
Create groups to work?

### ISSUE THREAD

**Issue by bicatcho11** [Qbox-project/qbx_core#381]
### The problem

I have a question: Does the project contain the functions included in the legal functions?
The working system supports groups
For example, if, for example, the tracker job
Can two players work on the same shipment when it is transported and divided among them?
For example, one person drives the vehicle and another delivers the goods after arriving at the place?

### Ideal solution

Create a group and join it

**Comment by TonybynMp4** [comment]
This makes absolutely no sense whatsoever.
But if i understood the example correctly then no, there is no group system.

**Comment by mafewtm** [comment]
Closing as this is stale and the functionality for a activity group system is not being worked on at this time.
