### ISSUE TITLE
Deleting a character fails on clean qbox installs

### ISSUE THREAD

**Issue by solareon** [Qbox-project/qbx_core#398]
### Summary

Deleting a character fails on clean qbox installs

### Reproduction

Install qbox, make a character, and then delete them.

### Expected behavior

Character is deleted

### Actual behavior

Database errors on server console
![image](https://github.com/Qbox-project/qbx_core/assets/769465/bea1dd8b-a556-4d10-be59-3d71f340c879)

### Additional context

https://github.com/Qbox-project/qbx_core/blob/4a2aae8c1db4ee115e94176ca53b578359c806fa/config/server.lua#L63-L76

Some of these tables exist for backwards compatibility but we don't check for their presence prior to deleting.

### Current Version

v1.7.1

### Custom Resources

n/a

**Comment by Apriawanto15** [comment]
I don't think it's just clean, I also tried full resources when deleting characters but it still doesn't work when the tables in the config are not deleted or are not used

**Comment by Manason** [comment]
Is this really a bug? I think it's a reasonable expectation that fresh installs are required to go through the config and configure the core according to their setup.

**Comment by Manason** [comment]
I'm not sure that we should change the config/code for this issue. However, it may be useful to add documentation or in-line comments to increase awareness if users encounter this.
