### ISSUE TITLE
Routing buckets related to vehicles is not functioning properly

### ISSUE THREAD

**Issue by SKITTLE6969** [Qbox-project/qbx_core#402]
### Summary

i recently got couple of reports regarding seeing vehicles going underground when their routing bucket changes, after investigating i noticed that it mainly happes when coming out from apartment or a shell

### Reproduction

happens when there alot of players around you cannot reproduce alone

### Expected behavior

.

### Actual behavior

.

### Current Version

latest

### Custom Resources

n/a

**Comment by soniXx123** [comment]
having the same issue still with the latest version. 

https://cdn.discordapp.com/attachments/1067102788615688294/1220689347880419338/20240321-1733-00.9977239.mp4
