### ISSUE TITLE
player_groups deletes

### ISSUE THREAD

**Issue by icarusmods** [Qbox-project/qbx_core#408]
### Summary

Wipe of player_groups when loading character

### Reproduction

1. set job
2. log out
3. log in

### Expected behavior

Save job that i had on last player save

### Actual behavior

Player jobs wipe on load

### Additional context

The issue isnt when the user unloads, its saved up until the moment the user loads, then it deletes their characters associated jobs

### Current Version

1.7.1

### Custom Resources

randol_multijob (i believe unrelated but just in case)

**Comment by Manason** [comment]
Someone else suggested that the player_jobs table might be conflicting from renewed-phone, which I believe might be the same name as qb-phone. Are you using this phone?

**Comment by Manason** [comment]
Confirmed that this is due to player_groups table being using by renewed-phone to supply non job/gang groups. Since this is a generic table name, qbx should probably rename the table to qbx_player_groups

**Comment by Manason** [comment]
Disregard, got confused by the names. @icarusmods did you figure out this issue?

**Comment by Manason** [comment]
@icarusmods Could this issue be that /setjob overwrites your current primary job? Unless you've set the convars to false that is https://github.com/Qbox-project/txAdminRecipe/blob/main/server.cfg#L34-L35
