### ISSUE TITLE
[REQUEST] Keys Core Commands

### ISSUE THREAD

**Issue by MrNewb** [Qbox-project/qbx_core#420]
### The problem

Typical key systems store a table and I understand why this was done this way but to discourage core edits can you pass the entity and then pull the plate later.

 https://github.com/Qbox-project/qbx_core/blob/8f88f1cc1ccba23bef784e39ae5fa9abd9e7409f/server/commands.lua#L160

### Ideal solution

https://github.com/Qbox-project/qbx_core/blob/8f88f1cc1ccba23bef784e39ae5fa9abd9e7409f/config/server.lua#L130

This line to pass the entity and then pull the plate in https://github.com/Qbox-project/qbx_core/blob/8f88f1cc1ccba23bef784e39ae5fa9abd9e7409f/config/server.lua#L130
after its been passed, this gives freedom and keeps the core from being edited to get a value we already had

### Alternative solutions

Not doing it and making me sad

### Additional context

This is motivated by my own interest's in compatibility.

**Comment by Manason** [comment]
It's a bit difficult to understand this. If it's a one line change can you make a PR?

**Comment by void-hub-scripts** [comment]
![Uploading John-F.-Kennedy-PNG-HD-Isolated-2230274760.png…]()

**Comment by MrNewb** [comment]
Ty, Solareon. I was worried id break some external script to the core but your approach is solid. -- Resolved
