### ISSUE TITLE
Vehicle spawning in buckets does not work 

### ISSUE THREAD

**Issue by alberttheprince** [Qbox-project/qbx_core#435]
### Summary

Spawning a car outside of the main bucket (outside of bucket 0) does not work

### Reproduction

1. Spawn a vehicle in any bucket besides bucket 0
2. Vehicle will not spawn
3. Set yourself in the main (0) bucket
4. Vehicle spawns as soon as you enter bucket 0

### Expected behavior

It's expected that a vehicle will spawn in your bucket

### Actual behavior

Does not spawn and gets "preloaded" for when you return to bucket 0

### Additional context

This used to work, then broke at some point in qbox development

### Current Version

current

### Custom Resources

N/A

**Comment by solareon** [comment]
Does the server side vehicle spawn native even support creating it in a different bucket?

I presume you are setting yourself to a different bucket then trying like /car?

**Comment by alberttheprince** [comment]
Correct. 

I'm not sure, but at some point this was working. Vehicles continue to be spawned in the world if you go to another bucket, Im not sure if these are done on the client or server.

**Comment by solareon** [comment]
> Correct.
> 
> I'm not sure, but at some point this was working. Vehicles continue to be spawned in the world if you go to another bucket, Im not sure if these are done on the client or server.

I think when the spawns were done client side then they inherited the routing bucket of the client but the server doesn't know about it. My PR should fix that but needs some testing
