### ISSUE TITLE
[Possible Bug] Duty Status is Setting Incorrectly at Login (Not defaulting to what the shared/jobs.lua has in place)

### ISSUE THREAD

**Issue by ItsVinnyX** [Qbox-project/qbx_core#443]
### Summary

Duty status is not defaulting to what the shared/jobs.lua has.

### Reproduction

1. Make sure to go on/off duty (Make sure duty is true/false). Preferrably go on duty to make it easier to identify.
2. After going on/off duty, logoff (F8 Quit).
3. Log back on. After loading, check your duty status.
4. It should be set to whatever your last duty status is.

### Expected behavior

Since I have defaultDuty set to false within shared/jobs.lua it should be forcing the player when they login to off-duty. Yes, I have ForceJobDefaultDutyAtLogin set to true.

### Actual behavior

After updating from 1.6.1 qbx_core, players will login on duty when the defaultDuty status is set to false in shared/jobs.lua. Within the shared/main.lua ForceJobDefaultDutyAtLogin is set to true.

### Additional context

N/A

### Current Version

v1.10.1

### Custom Resources

Nothing that would directly effect this issue. It only happened after an upgrade from 1.6.1.

**Comment by Scullyy** [comment]
Confirmed this issue and fixed it

**Comment by FjamZoo** [comment]
Fixed: https://github.com/Scullyy/qbx_core/commit/84f92559fe99552dc37bbc15675a2cd0e08c1210
