### ISSUE TITLE
Health draining instantly after spawning

### ISSUE THREAD

**Issue by Exu9xx** [Qbox-project/qbx_core#456]
### Summary

after latest qbx core update my health is draining fully from 100 to 0 in like 30 seconds

### Reproduction

1. Downloaded newest qbx_core
2. Restarted server
3. Jumped in and figured out that theres bug

### Expected behavior

Fix this issue as soon as possible

### Actual behavior

Health draining even your thirst and hunger level is full

### Current Version

1.11.0

### Custom Resources

no

**Comment by Manason** [comment]
I'm running this version but it's not occurring for me. What other resources are you running that could be interacting with core here?

**Comment by Exu9xx** [comment]
> I'm running this version but it's not occurring for me. What other resources are you running that could be interacting with core here?

It was only on latest qbx core, once i downgrade it back it goes back to normal despite any other resource

**Comment by Manason** [comment]
> > I'm running this version but it's not occurring for me. What other resources are you running that could be interacting with core here?
> 
> It was only on latest qbx core, once i downgrade it back it goes back to normal despite any other resource

Right. I just don't know how to investigate this since I can't reproduce on my server. Are you running default recipe resources, or do have any idea what the underlying issue might be?

**Comment by iplayer1337fivem** [comment]
I just downloaded a new build, and removed some scripts due, I dont need them for this build. But its the same, 69 seconds alive.
Here is the ressources im using atm. if its any helpful
![image](https://github.com/Qbox-project/qbx_core/assets/69944020/13bb540e-5a65-4dca-b4cd-6e98f49bab2b)

no hanky panky with another stuff, just clean straightforward installed.

**Comment by animajota** [comment]
I fixed this problem by going to you txadmin -> settings, and changing OneSync from "LEGACY" to "ON (with infinity)"
![gDrbcZKt1h](https://github.com/Qbox-project/qbx_core/assets/81733693/a9bab61c-2056-4bc2-a722-bd160434d84f)

**Comment by Manason** [comment]
@Exu9xx Are you on one sync legacy?

**Comment by Exu9xx** [comment]
> @Exu9xx Are you on one sync legacy?

yea, now i changed to On  and it works.. strange things huh.
