### ISSUE TITLE
Can't select a birthday after changing date format

### ISSUE THREAD

**Issue by animajota** [Qbox-project/qbx_core#458]
### Summary

Birthday in character cant not be selected after changing the format

### Reproduction

1. change the date format and then change the dateMin and dateMax in Config->client.lua
![badformating](https://github.com/Qbox-project/qbx_core/assets/81733693/be1c3456-f2ba-47e9-b7f1-20cfb970fb13)
3.  Create new character in server
4.  Change the birthday to any year that you want (must not be the default one) 

### Expected behavior

Being able to change the date correctly

### Actual behavior

When trying to input a new year, you can't select any month or day, and you can't go back to previous days. Days will be grayout once you change the default date.

![actual](https://github.com/Qbox-project/qbx_core/assets/81733693/dcffaec9-2662-4210-9f1a-6a65b724e949)

### Current Version

v1.11.0

### Custom Resources

none

**Comment by mafewtm** [comment]
I am unable to reproduce this issue. I've set my format as per your parameters and am able to select any date I wish
