### ISSUE TITLE
Newly created characters skip character creation/customisation

### ISSUE THREAD

**Issue by LordChunk** [Qbox-project/qbx_core#464]
### Summary

Newly created characters skip character creation screen

### Reproduction

1. Scaffold a new qbox server using [https://github.com/Qbox-project/txAdminRecipe/blob/8544dfc6d2f6f53cfea209daa21feee37eed1027/qbox.yaml](the full recipe)
2. Join the server and create a new character
3. Submit the form containing the character name, dob, sex and nationality. 
4. The new character will spawn in the room where the character selection camera is placed.

### Expected behavior

A character creation screen should be triggered after submitting step 3 and the new player should be spawned in their apartment. 

### Actual behavior

The player is spawned as a standard male of female ped in the character selection room.

### Additional context

When relogging, you might also get assigned a different default ped when selecting your newly created character. 

Setting ``startingApartment`` to ``false`` in ``qbx_core/config/client.lua`` does trigger the character creation screen and is a workaround if you don't mind spawning your new characters in a different location.

### Current Version

v1.11.1

### Custom Resources

None

**Comment by ArturMichalak** [comment]
Best to install qbx_properties.
`git clone https://github.com/Qbox-project/qbx_properties.git` in [qbx] catalog or extract zip in this catalog.
 I have heard that it even works quite well already.

**Comment by LordChunk** [comment]
qbx_properties seems to still be a work in progress. Do you know to what extend it already covers functionality offered by: ``qbx_houses`` and ``qbox_apartments``?

**Comment by ArturMichalak** [comment]
That's all I know
![obraz](https://github.com/Qbox-project/qbx_core/assets/36608116/83e1083a-bcb2-4fcb-8424-a4e144fb9a35)
https://github.com/Qbox-project/txAdminRecipe/pull/67

**Comment by Manason** [comment]
Believe this is solved. If not, please reopen.
