### ISSUE TITLE
Hunger level increments only after first burger

### ISSUE THREAD

**Issue by artur-michalak** [Qbox-project/qbx_core#470]
### Summary

Metadata desynchronization problem still occurs, i think.
Enforcing sychronization helps.

### Reproduction

1. Set hunger level to 10
2. Buy 2 burgers in a shop
3. Eat bought food
4. No hunger bar update after eating second burger

1. Set hunger level to 10
2. Spawn 3 twerks candies `/additem 1 twerks_candy 3`
3. Eat food
4. Food level in admin menu does not update

### Expected behavior

Update metadata on changes

### Actual behavior

as in reproduction

### Additional context

![obraz](https://github.com/Qbox-project/qbx_core/assets/36608116/99c1c4a3-7376-426c-be2b-3b7a30359a3a)

I made a hotfix in smallresources that partially fixes this, but the fix needs to be done qbx_core.

https://github.com/Qbox-project/qbx_smallresources/pull/99/files

### Current Version

v1.12.0

### Custom Resources

unreleased version of qbx_vehiclekeys

**Comment by ArturMichalak** [comment]
After some time there is synchronization, but not immediately.

**Comment by TonybynMp4** [comment]
> After some time there is synchronization, but not immediately.

So it works as expected, great.

**Comment by ArturMichalak** [comment]
10 burgers without affecting hunger level is expected?

**Comment by TonybynMp4** [comment]
> 10 burgers without affecting hunger level is expected?

Hunger level ~= metadata

**Comment by TonybynMp4** [comment]
Think this can be closed now?

**Comment by solareon** [comment]
> Think this can be closed now?

Soon ™️

**Comment by TonybynMp4** [comment]
nvm, thought it wasn't a problem for a long time, forgot qbox still supported qb
