### ISSUE TITLE
[3rdParty] Vehicleskeys

### ISSUE THREAD

**Issue by l3oncoder** [Qbox-project/qbx_core#485]
### The problem

So I notice we have givekeys and haskeys that by default are hard baked into the core,

Is it not possible for us to have an way to include our own exports from from config, as current we has to edit server/commands.lua & qb/bridge/events.lua etc

### Ideal solution

Add away for us to specify our own vehiclekeys export, server & client sided

**Comment by mafewtm** [comment]
It's not hardcoded at all? Look in `qbx_core/config/client.lua` and `qbx_core/config/server.lua`.

**Comment by mafewtm** [comment]
Closing as this is already implemented within out configs as I have shown above.
