### ISSUE TITLE
v1.18.0 Bugs

### ISSUE THREAD

**Issue by Manason** [Qbox-project/qbx_core#549]
High level tracking and test plan

- [x] Eat food -> hunger goes up in database and UI
- [x] Open NPC vehicle trunk with plate partially matching a player vehicle id that has trunk items -> those trunk items are not in the NPC trunk
- [x] in a 3rd party resource, create the QBCore object and print shared.items -> shared.items is not empty
- [x] add/remove money -> verify that money UI updates to sync with new inventory money
- [ ] qb-inventory database conversion to ox_inventory -> exists

**Comment by solareon** [comment]
I believe the issue was PlayerData.items not being populated. QBCore.Shared.Items does populate correctly.
