### ISSUE TITLE
Money item ox_inventory is not synchronized

### ISSUE THREAD

**Issue by DerHobbs** [Qbox-project/qbx_core#557]
### Summary

The cash I receive or pay, no matter where, is only added and deducted in the hud, the item money is not synced

### Reproduction

The easiest way is to use the command /addmoney, the money is added in the HUD, but not in the inventory (Item money)

### Expected behavior

I expect the "Money" item to always match the actual cash amount, just like it is displayed in the HUD.

### Actual behavior

I’m using ox_inventory, and when I purchase something from a shop that comes with ox_inventory, everything works as expected. The money is deducted, and the corresponding amount is also subtracted from the money item in my inventory. However, when I’m supposed to receive money from somewhere else, I can see it in the HUD, but the money item is not added to my inventory. This results in the money disappearing when I log out because I never actually received the item.

Additionally, when I go to the ATM, the money in my inventory doesn’t update, whether I deposit or withdraw. The amount of the money item remains the same, only the HUD display is accurate.

What have I tried so far? I’ve re-downloaded ox_inventory, ox_libs, and qbox core and placed them on the server without any changes. The problem remains the same. Even after disabling all unnecessary resources and clearing the cache, nothing I do seems to fix the issue. The problem persists no matter what steps I take.

After further testing, I’ve noticed that shops integrated into the inventory work as expected. However, if I purchase something elsewhere or receive treatment at the hospital, the money in the inventory (money item) is not deducted or added when selling.

This issue allows players to drop their money after a purchase and then pick it up again, effectively letting them get everything for free.

I’ve already raised this issue with ox, but they believe it might be related to the framework.

Any ideas on what could be causing this? I’m at a loss.

Best regards

ox_lib version: 3.25.0
ox_inventory version: 2.42.0
qbox version: 1.18.0
GameBuild 3258
Artifacts 9655

https://streamable.com/id9u3j

### Current Version

1.18.0

### Custom Resources

That would be a long list, but as already written, the problem exists even without custom resources

**Comment by mafewtm** [comment]
Try downloading qbx_core by using the code button. We pushed a fix for money but haven't pushed a release yet. Check and see if it's sorted.

**Comment by Manason** [comment]
This is a known issue with v1.18.0 and ox_inventory v2.42.0. You'll need to downgrade to latest stable (v1.17.2) to have this working.
