### ISSUE TITLE
syntax error found

### ISSUE THREAD

**Issue by VerserVarlin** [Qbox-project/qbx_core#581]
### Summary

was getting a syntax error in qbx_core\modules\lib.lua. fix included

### Reproduction

skip

### Expected behavior

how you have the code block line 121-127

```
function qbx.table.size(tbl)
    local size = 0
    for _ in pairs(tbl) do
        size += 1
    end
    return size
end
```

here is a fix for it

```
function qbx.table.size(tbl)
    local size = 0
    for _ in pairs(tbl) do
        size = size + 1
    end
    return size
end
```

### Actual behavior

skip

### Current Version

1.19.0

### Custom Resources

no

**Comment by Manason** [comment]
> ### Summary
> 
> was getting a syntax error in qbx_core\modules\lib.lua. fix included
> ### Reproduction
> 
> skip
> ### Expected behavior
> 
> how you have the code block line 121-127
> 
> ```
> function qbx.table.size(tbl)
>     local size = 0
>     for _ in pairs(tbl) do
>         size += 1
>     end
>     return size
> end
> ```
> 
> here is a fix for it
> 
> ```
> function qbx.table.size(tbl)
>     local size = 0
>     for _ in pairs(tbl) do
>         size = size + 1
>     end
>     return size
> end
> ```
> 
> ### Actual behavior
> 
> skip
> ### Additional context
> 
> _No response_
> ### Current Version
> 
> 1.19.0
> ### Custom Resources
> 
> no

What syntax error were you getting? What game version are you running? Have you modified qbx_core at all?

**Comment by mafewtm** [comment]
That's what [this](https://github.com/Qbox-project/qbx_core/blob/main/.vscode/settings.json#L3) is for

**Comment by VerserVarlin** [comment]
> That's what [this](https://github.com/Qbox-project/qbx_core/blob/main/.vscode/settings.json#L3) is for

if so then i should not be getting a syntax error from it, right?

**Comment by Manason** [comment]
> > That's what [this](https://github.com/Qbox-project/qbx_core/blob/main/.vscode/settings.json#L3) is for
> 
> if so then i should not be getting a syntax error from it, right?

Did you figure out the reason for the syntax error?
