### ISSUE TITLE
qbx_core:GetOfflinePlayer Runtime Error - not handling nil gracefully

### ISSUE THREAD

**Issue by zozomanx** [Qbox-project/qbx_core#608]
### Summary

When passing a Citizen ID that doesn't exist to GetOfflinePlayer a runtime error occurs

### Reproduction

1. Enter in an non-existant Citizen ID into exports.qbx_core:GetOfflinePlayer() - Use my provided commands to test
2. Attempt to run that export via the command
3. Get error

### Expected behavior

Be returned a nil value if that citizen ID doesn't exist or have it be handled the same way exports.qbx_core:GetPlayerByCitizenId() does.

exports.qbx_core:GetPlayer() and exports.qbx_core:GetPlayerByCitizenId() handle an incorrect CID or Citizen ID gracefully and do not generate runtime errors.

### Actual behavior

A runtime error occurs and the program exits.

### Additional context

**This is the runtime error that gets generated**:

[     script:rfl_core] command 'gunband' failed to execute!
[     script:rfl_core] @rfl_core/server/server.lua:95:
[     script:rfl_core]  An error occurred while calling export `GetOfflinePlayer` in resource `qbx_core`:
[     script:rfl_core]   citizen:/scripting/lua/scheduler.lua:739: SCRIPT ERROR: @qbx_core/server/storage/players.lua:115: attempt to index a nil value (local 'player')
[     script:rfl_core]   > fetchPlayerEntity (@qbx_core/server/storage/players.lua:115)
[     script:rfl_core]   > ref (@qbx_core/server/player.lua:57)
[     script:rfl_core]   > rawQuery (@oxmysql/dist/build.js:27077)
[     script:rfl_core]   > processTicksAndRejections (node:internal/process/task_queues:96)

**Commands I used to debug with and you can easily copy and paste**:

```
lib.addCommand('niltestid', {
    help = 'Test command',
    params = {
        { name = 'id', type = 'string' },
    }
}, function(source, args)
    local player = exports.qbx_core:GetPlayer(args.id)
    print(player)
    if not player then
        TriggerClientEvent('ox_lib:notify', source, { title = 'Error', description = 'Invalid argument', position = 'top', type = 'error' })
        return
    end
end)

lib.addCommand('niltestcid', {
    help = 'Test command',
    params = {
        { name = 'id', type = 'string'},
    }
}, function(source, args)
    local player = exports.qbx_core:GetPlayerByCitizenId(args.id)
    print(player)
    if not player then
        TriggerClientEvent('ox_lib:notify', source, { title = 'Error', description = 'Invalid argument', position = 'top', type = 'error' })
        return
    end
end)

lib.addCommand('niltestcidoffline', {
    help = 'Test command',
    params = {
        { name = 'id', type = 'string' },
    }
}, function(source, args)
    local player = exports.qbx_core:GetOfflinePlayer(args.id)
    print(player)
    if not player then
        TriggerClientEvent('ox_lib:notify', source, { title = 'Error', description = 'Invalid argument', position = 'top', type = 'error' })
        return
    end
end)
```

**If you run /niltestcidoffline FAKE123 you will get the runtime error.**

### Current Version

1.20.1

### Custom Resources

A small script I'm writing

**Comment by D4isDAVID** [comment]
This is already fixed by #595, please use [v1.21.0](https://github.com/Qbox-project/qbx_core/releases/tag/v1.21.0).
