### ISSUE TITLE
Error when logging in some players

### ISSUE THREAD

**Issue by DerHobbs** [Qbox-project/qbx_core#636]
### Summary

Some players log in and this is what it says in the console

### Reproduction

You can reproduce it, it happens when a player wants to log in with license instead of license2,
He then cannot log in and only has a black screen

### Expected behavior

Since the last update, this appears in my server console when a player who only has a license and no license2 tries to log in
![Screenshot_4](https://github.com/user-attachments/assets/f4534fe4-110a-4eac-91a0-1dcc0863f474)

### Actual behavior

No error

### Current Version

1.22.1

### Custom Resources

too much to do with the login perhaps 17mov_charaktersystem

**Comment by DerHobbs** [comment]
Ok you can reproduce it, it happens when a player wants to log in with license instead of license2,
He then cannot log in and only has a black screen

**Comment by mafewtm** [comment]
This should be fixed in 1.22.2. Give it a test and see.
