### ISSUE TITLE
Vehicle Keys search function suggestion

### ISSUE THREAD

**Issue by ErnyDV** [Qbox-project/qbx_core#643]
### The problem

I searched around the files and didn't find any way of disabling the search key functionality maybe I just missed it but I wasn't able to find it inside the files in the config folder.

### Ideal solution

add a line in the config wherever you guys see fit that we can just change the value from true to false to disable the functionality.

**Comment by mafewtm** [comment]
this should be in qbx_vehiclekeys. qbx_core does not deal with vehiclekeys.
